name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  quality:
    name: コード品質チェック
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      
      - name: 依存関係インストール
        run: pnpm install --frozen-lockfile
      
      - name: 型チェック
        run: pnpm typecheck
      
      - name: フィーチャー境界チェック
        run: pnpm check:boundaries
      
      - name: 全体チェック
        run: |
          cp .env.ci .env.local 2>/dev/null || true
          pnpm check

  test:
    name: テスト実行
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      
      - name: 依存関係インストール
        run: pnpm install --frozen-lockfile
      
      - name: 単体テスト
        run: pnpm test:unit
      
      - name: Playwrightブラウザインストール
        run: pnpm exec playwright install chromium --with-deps
      
      - name: E2Eテスト
        run: pnpm test:e2e
      
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            test-results/
            playwright-report/
          retention-days: 30

  build:
    name: ビルドチェック
    runs-on: ubuntu-latest
    needs: [quality, test]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      
      - name: 依存関係インストール
        run: pnpm install --frozen-lockfile
      
      - name: プロダクションビルド
        run: pnpm build
      
      - name: Preflightチェック
        run: pnpm preflight